/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Clases.Conexion;
import Clases.Empresa;
import Clases.Usuario;
import Negocio.TiendaNegocio;
import Negocio.UsuarioNegocio;
import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ivan
 */
public class AsignarTiendaPanel extends javax.swing.JPanel {

    ResultSet rss;
    DefaultTableModel ListarTablaUsuarios;
    DefaultTableModel ListarTablaEmpresa;
    DefaultTableModel tablaauxiliarUsuarios;
    Empresa empresa =  new Empresa();
    TiendaNegocio tiendaN = new TiendaNegocio();
    UsuarioNegocio usuarioN = new UsuarioNegocio();
    /**
     * 
     * 
     * Creates new form AsignarTienda
     */
    public AsignarTiendaPanel() throws SQLException, ClassNotFoundException {
        
        ListarTablaUsuarios = new DefaultTableModel(null,getColumna());
        
        setFilas();
        ListarTablaEmpresa = new DefaultTableModel(null,getColumnaEmpresa());
        
       // setFilasEmpresa();
        initComponents();
               this.TableListarEmpresas.getColumnModel().getColumn(2).setMaxWidth(2);
           this.TableListarEmpresas.getColumnModel().getColumn(2).setMinWidth(2);
           this.TableListarEmpresas.getColumnModel().getColumn(2).setPreferredWidth(2);
                   this.TableListarEmpresas.getColumnModel().getColumn(3).setMaxWidth(3);
           this.TableListarEmpresas.getColumnModel().getColumn(3).setMinWidth(3);
           this.TableListarEmpresas.getColumnModel().getColumn(3).setPreferredWidth(3);
        rss= empresa.getEmpresas();
         while(rss.next()){
             CbxEmpresa.addItem(rss.getString("NOMBRE_EMPRESA"));
         }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAsignar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableListarUsuarios = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableListarEmpresas = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        CbxEmpresa = new javax.swing.JComboBox<>();
        btnRevisarAsignacion = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnQuitarAsignacion = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtRut = new javax.swing.JTextField();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Asignación de tienda", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Georgia", 3, 24))); // NOI18N

        btnAsignar.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        btnAsignar.setText("ASIGNAR");
        btnAsignar.setToolTipText("");
        btnAsignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignarActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Encargados de tienda sin asignar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Georgia", 3, 14))); // NOI18N

        TableListarUsuarios.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        TableListarUsuarios.setModel(ListarTablaUsuarios);
        jScrollPane1.setViewportView(TableListarUsuarios);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tiendas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Georgia", 3, 14))); // NOI18N

        TableListarEmpresas.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        TableListarEmpresas.setModel(ListarTablaEmpresa);
        TableListarEmpresas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seleccionEncargado(evt);
            }
        });
        jScrollPane2.setViewportView(TableListarEmpresas);

        jLabel2.setFont(new java.awt.Font("Georgia", 3, 12)); // NOI18N
        jLabel2.setText("Empresa");

        CbxEmpresa.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        CbxEmpresa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar Empresa" }));
        CbxEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbxEmpresaActionPerformed(evt);
            }
        });

        btnRevisarAsignacion.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        btnRevisarAsignacion.setText("Revisar asignación");
        btnRevisarAsignacion.setToolTipText("Se quitara el encargado que tenga asignada la tienda");
        btnRevisarAsignacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRevisarAsignacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(CbxEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRevisarAsignacion))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(CbxEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRevisarAsignacion)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Encargado de tienda asignado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Georgia", 3, 14))); // NOI18N

        btnQuitarAsignacion.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        btnQuitarAsignacion.setText("Quitar asignación ");
        btnQuitarAsignacion.setToolTipText("Se quitara el encargado que tenga asignada la tienda");
        btnQuitarAsignacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitarAsignacionActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        jLabel1.setText("Nombre Encargado");

        jLabel3.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        jLabel3.setText("Rut Encargado");

        txtNombre.setEnabled(false);
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        txtRut.setEnabled(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtRut, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnQuitarAsignacion)))
                .addGap(175, 175, 175))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnQuitarAsignacion))
                .addGap(0, 20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAsignar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancelar)))
                .addContainerGap(122, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAsignar)
                        .addComponent(btnCancelar)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void CbxEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbxEmpresaActionPerformed

          int idEmpresa=0;
        try {
            rss= empresa.getEmpresasID(CbxEmpresa.getSelectedItem().toString());
            while (rss.next()){
                idEmpresa= rss.getInt(1);
            }
            rss.close();
            setFilasEmpresa(idEmpresa);
        
           
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(RegistarUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_CbxEmpresaActionPerformed

    private void seleccionEncargado(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seleccionEncargado
    
    }//GEN-LAST:event_seleccionEncargado

    private void btnRevisarAsignacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRevisarAsignacionActionPerformed
     
            // TODO add your handling code here:TableListarEmpresas
            rss = null;
txtRut.setText("");
txtNombre.setText(""); 
        try{
            if (ListarTablaEmpresa.getValueAt(TableListarEmpresas.getSelectedRow(),2)== null) {
                JOptionPane.showMessageDialog(null, "Tienda no posee un encargado","", JOptionPane.INFORMATION_MESSAGE);
            }else{
              rss = usuarioN.getUsuarioRutNombre(ListarTablaEmpresa.getValueAt(TableListarEmpresas.getSelectedRow(),2).toString());
                 while (rss.next()){
                txtRut.setText(rss.getString(1));
                txtNombre.setText(rss.getString(2));
            } 
            }
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(AsignarTiendaPanel.class.getName()).log(Level.SEVERE, null, ex);
        }     
    }//GEN-LAST:event_btnRevisarAsignacionActionPerformed

    private void btnQuitarAsignacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarAsignacionActionPerformed
        try {
            // tiendaN.eliminarAsignacion(Integer.parseInt(ListarTablaEmpresa.getValueAt(TableListarEmpresas.getSelectedRow(),2).toString()));
            if (txtRut.getText().equals("") == false) {
              tiendaN.eliminarAsignacion(txtRut.getText()); }
            else{
                 JOptionPane.showMessageDialog(null, "","Verifique que exista algun encargado asociado, de no ser así asocie uno.", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(AsignarTiendaPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnQuitarAsignacionActionPerformed

    private void btnAsignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarActionPerformed
         try {
                tiendaN.agregarAsignacion(ListarTablaUsuarios.getValueAt(TableListarUsuarios.getSelectedRow(),0).toString(),
                       Integer.parseInt(ListarTablaEmpresa.getValueAt(TableListarEmpresas.getSelectedRow(),3).toString()));
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(AsignarTiendaPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
//        if (txtRut.getText() == "") {
//            JOptionPane.showMessageDialog(null, "","Verifique que exista algun encargado asociado", JOptionPane.INFORMATION_MESSAGE);
//        }else{
//          
//        }
        
        
    }//GEN-LAST:event_btnAsignarActionPerformed
    
    public String [] getColumna(){
        String columna[]= new String[]{"RUT","NOMBRE ENCARGADO"};
        return columna;
    }
       public String [] getColumnaEmpresa(){
        String columna[]= new String[]{"Nombre Tienda","Dirección Tienda","rut encargado","id empresa"};
        return columna;
    }
    public void setFilas() throws SQLException, ClassNotFoundException{
        Connection conn = null;
        Conexion conexion = new Conexion();
        conn=conexion.getConnection();
        Statement sentencia = null;
        ResultSet rs = null;
        String tipo=null;
        String query =  "select t.rut_usuario ,t.id_empresa FROM tienda t where t.rut_usuario is not null";
        sentencia =conn.createStatement();
        rs = sentencia.executeQuery(query);
        Object datos []=new Object[2];
       String query2 = "select u.RUT_USUARIO, u.NOMBRE_USUARIO ||' '||u.APEPA_USUARIO||' '||u.APEMA_USUARIO AS \"Nombre\" FROM USUARIO u ,tienda t  WHERE u.id_tipousuario = 2";
       
            while(rs.next()){
                             //  datos[i]= rs.getObject(i+1); Group by u.rut_usuario,u.nombre_usuario,u.apepa_usuario,u.apema_usuario order by u.rut_usuario
            query2 += " and u.rut_usuario <> '"+rs.getObject(1).toString()+"' ";
           } 
            query2 +=" Group by u.rut_usuario,u.nombre_usuario,u.apepa_usuario,u.apema_usuario order by u.rut_usuario";
        
         rs.close();
        sentencia =conn.createStatement();
        rs = sentencia.executeQuery(query2);
        
        while(rs.next()){
            for (int i = 0; i < 2; i++) {
                datos[i]= rs.getObject(i+1);
            }
            ListarTablaUsuarios.addRow(datos);
        }
        
        
        
    }

        public void setFilasEmpresa(int idempresa) throws SQLException, ClassNotFoundException{
            for (int i = 0; i < ListarTablaEmpresa.getRowCount(); i++) {
                ListarTablaEmpresa.removeRow(i);
            }
        Connection conn = null;
        Conexion conexion = new Conexion();
        conn=conexion.getConnection();
        Statement sentencia = null;
        ResultSet rs = null;
        String tipo=null;
        String query =  "select t.nombre_tienda AS \"Nombre tienda\", t.direccion_tienda as \"Direccion\",t.rut_usuario ,t.id_empresa FROM tienda t where t.id_empresa = "+idempresa+"";
        sentencia =conn.createStatement();
        rs = sentencia.executeQuery(query);
       
        Object datos []=new Object[4];
        
        while(rs.next()){
            for (int i = 0; i < 4; i++) {
                datos[i]= rs.getObject(i+1);
            }
            ListarTablaEmpresa.addRow(datos);
        }
        rs.close();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CbxEmpresa;
    public javax.swing.JTable TableListarEmpresas;
    public javax.swing.JTable TableListarUsuarios;
    private javax.swing.JButton btnAsignar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnQuitarAsignacion;
    private javax.swing.JButton btnRevisarAsignacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtRut;
    // End of variables declaration//GEN-END:variables
}
