/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Clases.Comuna;
import Clases.Empresa;
import Clases.Region;
import Clases.Tienda;
import Clases.Tipousuario;
import Clases.Usuario;
import Negocio.Registros;
import Negocio.UsuarioNegocio;
import Negocio.Validacion;
import java.awt.Color;
import java.awt.List;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
public class ModificarUsuarioP extends javax.swing.JPanel {

  ResultSet rss = null;
    ResultSet rssT= null;
     List lista =  new List(); 
     Usuario usuario = new Usuario();
       Tipousuario tusuario =new Tipousuario();
        Tienda tienda =new Tienda();
        Region region = new Region();
        Comuna comuna = new Comuna();
        Empresa empresa = new Empresa();
        Validacion validacion = new Validacion();
        UsuarioNegocio usuarioN = new UsuarioNegocio();
        
    public ModificarUsuarioP() throws SQLException, ClassNotFoundException {
        initComponents();
        if(usuario.getAdministradores()==1){
            CbxRoles.setEnabled(false);
        }
        
         LbErrorNombres.setVisible(false);
         LbErrorApepa.setVisible(false);
         LbErrorDireccion.setVisible(false);
         LbErrorClave.setVisible(false);
         LbErrorTelefono.setVisible(false);
         LbErrorApema.setVisible(false);
         LbErrorCorreo.setVisible(false);
        LbModificado.setVisible(false);
        jLabelComuna.setVisible(false);
        jLabelTienda.setVisible(false);
        
        
         rss= usuario.getUsuario();
         
         
         while(rss.next()){
             CbxRut.addItem(rss.getString("RUT_USUARIO"));
         }
         rss= tusuario.getTipoUsuario();
         while(rss.next()){
             CbxRoles.addItem(rss.getString("NOMBRE_TIPOUSUARIO"));
         }
         rss= empresa.getEmpresas();
         while(rss.next()){
             CbxEmpresa.addItem(rss.getString("NOMBRE_EMPRESA"));
         }
         rss= region.getRegiono();
         while(rss.next()){
             CbxRegion.addItem(rss.getString("NOMBRE_REGION"));
         }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        TxtCorreo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        TxtTelefono = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        CbxEmpresa = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        CbxRegion = new javax.swing.JComboBox<>();
        TxtNombre = new javax.swing.JTextField();
        CbxComuna = new javax.swing.JComboBox<>();
        TxtApellidoPaterno = new javax.swing.JTextField();
        LbModificado = new javax.swing.JLabel();
        TxtContrasena = new javax.swing.JTextField();
        LbErrorNombres = new javax.swing.JLabel();
        TxtDireccion = new javax.swing.JTextField();
        LbErrorApepa = new javax.swing.JLabel();
        CbxRoles = new javax.swing.JComboBox<>();
        LbErrorApema = new javax.swing.JLabel();
        CbxTiendas = new javax.swing.JComboBox<>();
        LbErrorClave = new javax.swing.JLabel();
        BtnModificar = new javax.swing.JButton();
        BtnCancelar = new javax.swing.JButton();
        LbErrorDireccion = new javax.swing.JLabel();
        LbErrorCorreo = new javax.swing.JLabel();
        CbxRut = new javax.swing.JComboBox<>();
        LbErrorTelefono = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        TxtApellidoMaterno = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabelTienda = new javax.swing.JLabel();
        jLabelComuna = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Modificación de usuario", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Georgia", 3, 18))); // NOI18N
        setRequestFocusEnabled(false);

        jLabel11.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        jLabel11.setText("Telefono");

        TxtCorreo.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        jLabel1.setText("Nombre");

        TxtTelefono.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        jLabel2.setText("Apellido Paterno");

        jLabel13.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel13.setText("Empresa");

        jLabel3.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        jLabel3.setText("Contraseña");

        jLabel4.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        jLabel4.setText("Rut");

        jLabel14.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel14.setText("Region");

        jLabel15.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        jLabel15.setText("Comuna");

        jLabel6.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        jLabel6.setText("Rol");

        CbxEmpresa.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        CbxEmpresa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Empresa" }));
        CbxEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbxEmpresaActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel7.setText("Tienda");

        CbxRegion.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        CbxRegion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Region" }));
        CbxRegion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbxRegionActionPerformed(evt);
            }
        });

        TxtNombre.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N

        CbxComuna.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N

        TxtApellidoPaterno.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N

        LbModificado.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        LbModificado.setForeground(new java.awt.Color(255, 0, 0));
        LbModificado.setText("jLabel5");

        TxtContrasena.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N

        LbErrorNombres.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        LbErrorNombres.setForeground(new java.awt.Color(255, 0, 0));
        LbErrorNombres.setText("jLabel16");

        TxtDireccion.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N

        LbErrorApepa.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        LbErrorApepa.setForeground(new java.awt.Color(255, 0, 0));
        LbErrorApepa.setText("jLabel17");

        CbxRoles.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        CbxRoles.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Rol" }));
        CbxRoles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbxRolesActionPerformed(evt);
            }
        });

        LbErrorApema.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        LbErrorApema.setForeground(new java.awt.Color(255, 0, 0));
        LbErrorApema.setText("jLabel18");

        CbxTiendas.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        CbxTiendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbxTiendasActionPerformed(evt);
            }
        });

        LbErrorClave.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        LbErrorClave.setForeground(new java.awt.Color(255, 0, 0));
        LbErrorClave.setText("jLabel19");

        BtnModificar.setBackground(new java.awt.Color(153, 255, 153));
        BtnModificar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BtnModificar.setText("Modificar");
        BtnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnModificarActionPerformed(evt);
            }
        });

        BtnCancelar.setBackground(new java.awt.Color(255, 153, 153));
        BtnCancelar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BtnCancelar.setText("Cancelar");
        BtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelarActionPerformed(evt);
            }
        });

        LbErrorDireccion.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        LbErrorDireccion.setForeground(new java.awt.Color(255, 0, 0));
        LbErrorDireccion.setText("jLabel20");

        LbErrorCorreo.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        LbErrorCorreo.setForeground(new java.awt.Color(255, 0, 0));
        LbErrorCorreo.setText("jLabel21");

        CbxRut.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        CbxRut.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar Usuario" }));
        CbxRut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbxRutActionPerformed(evt);
            }
        });

        LbErrorTelefono.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        LbErrorTelefono.setForeground(new java.awt.Color(255, 0, 0));
        LbErrorTelefono.setText("jLabel22");

        jLabel8.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        jLabel8.setText("Apellido Materno");

        TxtApellidoMaterno.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        jLabel10.setText("Dirección");

        jLabel9.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        jLabel9.setText("Correo Electronico");

        jLabelTienda.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabelTienda.setForeground(new java.awt.Color(255, 0, 0));
        jLabelTienda.setText("jLabel5");

        jLabelComuna.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabelComuna.setForeground(new java.awt.Color(255, 0, 0));
        jLabelComuna.setText("jLabel5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CbxRut, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TxtNombre)
                    .addComponent(TxtApellidoMaterno)
                    .addComponent(TxtApellidoPaterno)
                    .addComponent(TxtContrasena)
                    .addComponent(TxtDireccion)
                    .addComponent(TxtCorreo)
                    .addComponent(TxtTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LbErrorNombres, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(LbErrorApepa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LbErrorApema, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LbErrorClave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LbErrorDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LbErrorCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LbErrorTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTienda, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelComuna, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LbModificado, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                        .addGap(49, 49, 49)
                        .addComponent(BtnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CbxRoles, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CbxTiendas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CbxEmpresa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CbxRegion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CbxComuna, 0, 230, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CbxRoles))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CbxEmpresa))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CbxTiendas)
                            .addComponent(jLabelTienda))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CbxRegion))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CbxComuna)
                            .addComponent(jLabelComuna))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                            .addComponent(BtnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                        .addGap(41, 41, 41)
                        .addComponent(LbModificado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CbxRut))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TxtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                            .addComponent(LbErrorNombres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TxtApellidoPaterno)
                            .addComponent(LbErrorApepa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TxtApellidoMaterno)
                            .addComponent(LbErrorApema, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TxtContrasena)
                            .addComponent(LbErrorClave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TxtDireccion)
                            .addComponent(LbErrorDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TxtCorreo)
                            .addComponent(LbErrorCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TxtTelefono)
                            .addComponent(LbErrorTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 91, Short.MAX_VALUE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CbxEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbxEmpresaActionPerformed
        int idEmpresa=0;
        CbxTiendas.removeAllItems();
        try {
            rss= empresa.getEmpresasID(CbxEmpresa.getSelectedItem().toString());
            while (rss.next()){
                idEmpresa= rss.getInt(1);
            }
            rss = tienda.getTienda(idEmpresa);
            while (rss.next()){
                CbxTiendas.addItem(rss.getString(2));
            }
            rss.close();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(RegistarUsuario.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(RegistarUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_CbxEmpresaActionPerformed

    private void CbxRegionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbxRegionActionPerformed
        int idRegion=0;
        CbxComuna.removeAllItems();
        try {
            rss= region.getRegionID(CbxRegion.getSelectedItem().toString());

            while (rss.next()){
                idRegion= rss.getInt(1);

            }

            rss = comuna.getComunaxID(idRegion);
            while (rss.next()){
                CbxComuna.addItem(rss.getString(2));

            }

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(RegistarUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_CbxRegionActionPerformed

    private void CbxRolesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbxRolesActionPerformed
       if(CbxRoles.getSelectedIndex()==1){
                CbxTiendas.setEnabled(false);
                
                
                
            }else{
            CbxTiendas.setVisible(true);
                jLabel7.setVisible(true);
                
            }
        
    }//GEN-LAST:event_CbxRolesActionPerformed

    private void CbxTiendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbxTiendasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CbxTiendasActionPerformed

    private void BtnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModificarActionPerformed
        Registros registro = new Registros();
        int validado=0;
        LbErrorNombres.setVisible(false);
        LbErrorApepa.setVisible(false);
        LbErrorApema.setVisible(false);
        LbErrorClave.setVisible(false);
        LbErrorDireccion.setVisible(false);
        LbErrorCorreo.setVisible(false);
        LbErrorTelefono.setVisible(false);

        try {
            if (TxtNombre.getText().trim().length()<=0) {
                LbErrorNombres.setText("El nombre no puede estar vacio");
                LbErrorNombres.setVisible(true);
                validado++;
            };
            if(TxtApellidoPaterno.getText().trim().length()<=0){
                LbErrorApepa.setText("El apellido paterno no puede estar vacio");
                LbErrorApepa.setVisible(true);
                validado++;
            };
            if(TxtApellidoMaterno.getText().trim().length()<=0){
                LbErrorApema.setText("El apellido materno no puede estar vacio");
                LbErrorApema.setVisible(true);
                validado++;
            };
            if(TxtContrasena.getText().trim().length()<=0){
                LbErrorClave.setText("La clave no puede estar vacia");
                LbErrorClave.setVisible(true);
                validado++;
            };
            if(TxtDireccion.getText().trim().length()<=0){
                LbErrorDireccion.setText("La direccion no puede estar vacia");
                LbErrorDireccion.setVisible(true);
                validado++;
            };
            if(TxtCorreo.getText().trim().length()<=0){
                LbErrorCorreo.setText("El correo no puede estar vacio");
                LbErrorCorreo.setVisible(true);
                validado++;
            };
            if(TxtTelefono.getText().trim().length()<=0){
                LbErrorTelefono.setText("El telefono no puede estar vacio");
                LbErrorTelefono.setVisible(true);
                validado++;
            };
            if(validacion.validacionNumeros(TxtNombre.getText())){
                LbErrorNombres.setText("El nombre no puede tener numeros");
                LbErrorNombres.setVisible(true);
                validado++;
            };
            if(validacion.validacionNumeros(TxtApellidoPaterno.getText())){
                LbErrorApepa.setText("El apellido no puede tener numeros");
                LbErrorApepa.setVisible(true);
                validado++;
            };
            if(validacion.validacionNumeros(TxtApellidoMaterno.getText())){
                LbErrorApema.setText("El apellido no puede tener numeros");
                LbErrorApema.setVisible(true);
                validado++;
            };
            if(validacion.validacionLetras(TxtTelefono.getText())){
                LbErrorTelefono.setText("El telefono no puede tener letras");
                LbErrorTelefono.setVisible(true);
                validado++;
            };
            
            
            
           if(CbxComuna.getSelectedIndex()==-1){
               jLabelTienda.setText("Seleccione una comuna");
                jLabelComuna.setVisible(true);
                validado++;
                
            }
            if(CbxTiendas.getSelectedIndex()==-1){
                jLabelTienda.setText("Seleccione una tienda");
                jLabelTienda.setVisible(true);
                validado++;
                
            }
            if(validado>0){
                validado=0;

            }else{
                usuarioN.ModificarUsuario(TxtDireccion.getText(),TxtApellidoPaterno.getText(),
                    "N",CbxRut.getSelectedItem().toString(), TxtApellidoMaterno.getText(),
                    TxtContrasena.getText(),comuna.getIDxNombre(CbxComuna.getSelectedItem().toString()),
                    TxtNombre.getText(),tusuario.getIDxNombre(CbxRoles.getSelectedItem().toString()),
                    TxtCorreo.getText(),0,TxtTelefono.getText());
                JOptionPane.showMessageDialog(null, "Usuario Modificado Correctamente");// se cambio el mensaje a modo de ejemplo
                LbModificado.setText("Usuario Modificado Correctamente");

            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ModificarUsuario.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ModificarUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnModificarActionPerformed

    private void BtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelarActionPerformed
            LbErrorNombres.setVisible(false);
        LbErrorApepa.setVisible(false);
        LbErrorApema.setVisible(false);
        LbErrorClave.setVisible(false);
        LbErrorDireccion.setVisible(false);
        LbErrorCorreo.setVisible(false);
        LbErrorTelefono.setVisible(false);
        TxtNombre.setText("");
        TxtApellidoMaterno.setText("");
        TxtApellidoPaterno.setText("");
        TxtContrasena.setText("");
        TxtCorreo.setText("");
        TxtDireccion.setText("");
        TxtTelefono.setText("");
        CbxRut.setSelectedIndex(0);
        this.setVisible(false);
    }//GEN-LAST:event_BtnCancelarActionPerformed

    private void CbxRutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbxRutActionPerformed

        try {
            rss = usuario.getUsuarioRut(CbxRut.getSelectedItem().toString());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ModificarUsuario.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ModificarUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            while(rss.next()){
                TxtNombre.setText(rss.getString("NOMBRE_USUARIO"));
                TxtApellidoPaterno.setText(rss.getString("APEPA_USUARIO"));
                TxtApellidoMaterno.setText(rss.getString("APEMA_USUARIO"));
                TxtContrasena.setText(rss.getString("PASSWORD_USUARIO"));
                TxtDireccion.setText(rss.getString("DIRECCION_USUARIO"));
                TxtCorreo.setText(rss.getString("CORREO_USUARIO"));
                TxtTelefono.setText(rss.getString("TELEFONO_USUARIO"));

            }
        } catch (SQLException ex) {
            Logger.getLogger(ModificarUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_CbxRutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCancelar;
    private javax.swing.JButton BtnModificar;
    private javax.swing.JComboBox<String> CbxComuna;
    private javax.swing.JComboBox<String> CbxEmpresa;
    private javax.swing.JComboBox<String> CbxRegion;
    private javax.swing.JComboBox<String> CbxRoles;
    private javax.swing.JComboBox<String> CbxRut;
    private javax.swing.JComboBox<String> CbxTiendas;
    private javax.swing.JLabel LbErrorApema;
    private javax.swing.JLabel LbErrorApepa;
    private javax.swing.JLabel LbErrorClave;
    private javax.swing.JLabel LbErrorCorreo;
    private javax.swing.JLabel LbErrorDireccion;
    private javax.swing.JLabel LbErrorNombres;
    private javax.swing.JLabel LbErrorTelefono;
    private javax.swing.JLabel LbModificado;
    private javax.swing.JTextField TxtApellidoMaterno;
    private javax.swing.JTextField TxtApellidoPaterno;
    private javax.swing.JTextField TxtContrasena;
    private javax.swing.JTextField TxtCorreo;
    private javax.swing.JTextField TxtDireccion;
    private javax.swing.JTextField TxtNombre;
    private javax.swing.JTextField TxtTelefono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelComuna;
    private javax.swing.JLabel jLabelTienda;
    // End of variables declaration//GEN-END:variables
}
