/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Clases.Comuna;
import Clases.Empresa;
import Clases.Tienda;
import Clases.Tipousuario;
import Clases.Region;
import Negocio.Registros;
import Negocio.UsuarioNegocio;
import Negocio.Validacion;
import Negocio.HasharClave;
import java.awt.Color;
import java.awt.List;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.function.Function;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class RegistrarUsuarioP extends javax.swing.JPanel {
    ResultSet rss = null;
 UsuarioNegocio usuarioN = new UsuarioNegocio();
        Tipousuario tusuario =new Tipousuario();
        Tienda tienda =new Tienda();
        Region region = new Region();
        Comuna comuna = new Comuna();
        Empresa empresa = new Empresa();
     Validacion validacion = new Validacion();
    /**
     * Creates new form RegistrarUsuarioP
     */
    public RegistrarUsuarioP() throws ClassNotFoundException, SQLException {
       initComponents();
        // this.setLocationRelativeTo(null);
         //this.getContentPane().setBackground(Color.WHITE);
         LbErrorNombres.setVisible(false);
         LbErrorApepa.setVisible(false);
         LbErroDireccion.setVisible(false);
         LbErroRut.setVisible(false);
         LbErrorClave.setVisible(false);
         LbErrorTelefono.setVisible(false);
         LbErrorApMa.setVisible(false);
         LbErrorCorreo.setVisible(false);
        rss = tusuario.getTipoUsuario();
        while (rss.next()) {    
             CbxRoles.addItem(rss.getString("NOMBRE_TIPOUSUARIO"));
        }
         
        
         rss = region.getRegiono();
        while (rss.next()){
            CbxRegion.addItem(rss.getString("NOMBRE_REGION"));
        }
        rss = empresa.getEmpresas();
        while(rss.next()){
            CbxEmpresa.addItem(rss.getString("NOMBRE_EMPRESA"));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TxtApellidoMaterno = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        TxtCorreoElectronico = new javax.swing.JTextField();
        TxtTelefono = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        CbxEmpresa = new javax.swing.JComboBox<>();
        LbErrorNombres = new javax.swing.JLabel();
        LbErrorApepa = new javax.swing.JLabel();
        BtnCancelar = new javax.swing.JButton();
        LbErrorApMa = new javax.swing.JLabel();
        TxtNombre = new javax.swing.JTextField();
        LbErroRut = new javax.swing.JLabel();
        TxtApellidoPaterno = new javax.swing.JTextField();
        LbErrorClave = new javax.swing.JLabel();
        TxtRut = new javax.swing.JTextField();
        LbErroDireccion = new javax.swing.JLabel();
        TxtDireccion = new javax.swing.JTextField();
        LbErrorCorreo = new javax.swing.JLabel();
        CbxRoles = new javax.swing.JComboBox<>();
        LbErrorTelefono = new javax.swing.JLabel();
        CbxTiendas = new javax.swing.JComboBox<>();
        TxtContraseña = new javax.swing.JPasswordField();
        Region = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        CbxRegion = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        BtnRegistrar = new javax.swing.JButton();
        TxtRepetirContraseña = new javax.swing.JPasswordField();
        CbxComuna = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registro de Usuario", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Georgia", 3, 18))); // NOI18N
        setPreferredSize(new java.awt.Dimension(1033, 523));

        TxtApellidoMaterno.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        jLabel10.setText("Correo Electronico");

        jLabel11.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        jLabel11.setText("Telefono");

        TxtCorreoElectronico.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N

        TxtTelefono.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        TxtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtTelefonoActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        jLabel12.setText("Empresa");

        CbxEmpresa.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        CbxEmpresa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Empresa" }));
        CbxEmpresa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CbxEmpresaMouseClicked(evt);
            }
        });
        CbxEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbxEmpresaActionPerformed(evt);
            }
        });

        LbErrorNombres.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        LbErrorNombres.setForeground(new java.awt.Color(255, 0, 0));
        LbErrorNombres.setText("jLabel13");

        LbErrorApepa.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        LbErrorApepa.setForeground(new java.awt.Color(255, 0, 0));
        LbErrorApepa.setText("jLabel13");

        BtnCancelar.setBackground(new java.awt.Color(255, 153, 153));
        BtnCancelar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BtnCancelar.setText("Cancelar");
        BtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelarActionPerformed(evt);
            }
        });

        LbErrorApMa.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        LbErrorApMa.setForeground(new java.awt.Color(255, 0, 0));
        LbErrorApMa.setText("jLabel13");

        TxtNombre.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N

        LbErroRut.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        LbErroRut.setForeground(new java.awt.Color(255, 0, 0));
        LbErroRut.setText("jLabel13");

        TxtApellidoPaterno.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N

        LbErrorClave.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        LbErrorClave.setForeground(new java.awt.Color(255, 0, 0));
        LbErrorClave.setText("jLabel13");

        TxtRut.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N

        LbErroDireccion.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        LbErroDireccion.setForeground(new java.awt.Color(255, 0, 0));
        LbErroDireccion.setText("jLabel13");

        TxtDireccion.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N

        LbErrorCorreo.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        LbErrorCorreo.setForeground(new java.awt.Color(255, 0, 0));
        LbErrorCorreo.setText("jLabel13");

        CbxRoles.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        CbxRoles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbxRolesActionPerformed(evt);
            }
        });

        LbErrorTelefono.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        LbErrorTelefono.setForeground(new java.awt.Color(255, 0, 0));
        LbErrorTelefono.setText("jLabel13");

        CbxTiendas.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        CbxTiendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbxTiendasActionPerformed(evt);
            }
        });

        TxtContraseña.setToolTipText("ingrese contraseña");

        Region.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        Region.setText("Región");

        jLabel13.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        jLabel13.setText("Repita Contraseña");

        jLabel9.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        jLabel9.setText("Comuna");

        CbxRegion.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        CbxRegion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Región" }));
        CbxRegion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CbxRegionMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CbxRegionMousePressed(evt);
            }
        });
        CbxRegion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbxRegionActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        jLabel1.setText("Nombre");

        jLabel2.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        jLabel2.setText("Apellido Paterno");

        jLabel3.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        jLabel3.setText("Contraseña");

        jLabel4.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        jLabel4.setText("Rut");

        jLabel5.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        jLabel5.setText("Dirección");

        jLabel6.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        jLabel6.setText("Rol");

        jLabel7.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        jLabel7.setText("Tienda");

        BtnRegistrar.setBackground(new java.awt.Color(153, 255, 153));
        BtnRegistrar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BtnRegistrar.setText("Registrar");
        BtnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegistrarActionPerformed(evt);
            }
        });

        TxtRepetirContraseña.setToolTipText("ingrese contraseña");
        TxtRepetirContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtRepetirContraseñaActionPerformed(evt);
            }
        });

        CbxComuna.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        CbxComuna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbxComunaActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        jLabel8.setText("Apellido Materno");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtCorreoElectronico))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)))
                            .addComponent(jLabel13)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtRut, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                            .addComponent(TxtApellidoMaterno)
                            .addComponent(TxtContraseña)
                            .addComponent(TxtRepetirContraseña)
                            .addComponent(TxtTelefono)
                            .addComponent(TxtDireccion)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TxtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                            .addComponent(TxtApellidoPaterno))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LbErrorTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(LbErrorNombres, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                                    .addComponent(LbErrorApepa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(LbErrorApMa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(LbErroRut, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(LbErrorClave, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(84, 84, 84))
                            .addComponent(LbErrorCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LbErroDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Region, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(CbxComuna, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CbxRegion, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CbxRoles, javax.swing.GroupLayout.Alignment.LEADING, 0, 294, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CbxEmpresa, 0, 292, Short.MAX_VALUE)
                            .addComponent(CbxTiendas, 0, 292, Short.MAX_VALUE)
                            .addComponent(BtnRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                            .addComponent(BtnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CbxRoles))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Region, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CbxRegion))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CbxComuna))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CbxEmpresa))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CbxTiendas)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TxtNombre)
                                    .addComponent(LbErrorNombres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TxtApellidoPaterno)
                                    .addComponent(LbErrorApepa))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                            .addComponent(TxtApellidoMaterno)
                            .addComponent(LbErrorApMa))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtRut)
                            .addComponent(LbErroRut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                            .addComponent(TxtContraseña)
                            .addComponent(LbErrorClave))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(BtnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(TxtRepetirContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(TxtTelefono)
                                    .addComponent(LbErroDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TxtDireccion)
                                    .addComponent(LbErrorTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TxtCorreoElectronico)
                            .addComponent(LbErrorCorreo))
                        .addGap(1, 1, 1)
                        .addComponent(BtnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)))
                .addGap(59, 59, 59))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TxtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtTelefonoActionPerformed

    private void CbxEmpresaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CbxEmpresaMouseClicked

    }//GEN-LAST:event_CbxEmpresaMouseClicked

    private void CbxEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbxEmpresaActionPerformed
        // TODO add your handling code here:
        CbxTiendas.removeAllItems();
        int idEmpresa=0;
        rss = null;
        try {
            rss = empresa.getEmpresasID(CbxEmpresa.getSelectedItem().toString());
            //rss= tienda.getTienda(Integer.parseInt(CbxEmpresa.getSelectedItem().toString()));

            while (rss.next()){
                idEmpresa= rss.getInt(1);
            }

            rss = tienda.getTienda(idEmpresa);
            while (rss.next()){
                CbxTiendas.addItem(rss.getString(2));

            }
            rss.close();

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(RegistarUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_CbxEmpresaActionPerformed

    private void BtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelarActionPerformed
            LbErrorNombres.setVisible(false);
        LbErrorApepa.setVisible(false);
        LbErrorApMa.setVisible(false);
        LbErrorClave.setVisible(false);
        LbErroDireccion.setVisible(false);
        LbErrorCorreo.setVisible(false);
        LbErrorTelefono.setVisible(false);
        TxtNombre.setText("");
        TxtApellidoMaterno.setText("");
        TxtApellidoPaterno.setText("");
        TxtContraseña.setText("");
        TxtCorreoElectronico.setText("");
        TxtDireccion.setText("");
        TxtTelefono.setText("");
        TxtRut.setText("");
        CbxRoles.setSelectedIndex(0);
        CbxEmpresa.setSelectedIndex(0);
        CbxRegion.setSelectedIndex(0);
        this.setVisible(false);
    }//GEN-LAST:event_BtnCancelarActionPerformed

    private void CbxRolesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbxRolesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CbxRolesActionPerformed

    private void CbxTiendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbxTiendasActionPerformed

    }//GEN-LAST:event_CbxTiendasActionPerformed

    private void CbxRegionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CbxRegionMouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_CbxRegionMouseEntered

    private void CbxRegionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CbxRegionMousePressed

    }//GEN-LAST:event_CbxRegionMousePressed

    private void CbxRegionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbxRegionActionPerformed
      int idRegion=0;
        CbxComuna.removeAllItems();
        try {
            rss= region.getRegionID(CbxRegion.getSelectedItem().toString());

            while (rss.next()){
                idRegion= rss.getInt(1);

            }

            rss = comuna.getComunaxID(idRegion);
            while (rss.next()){
                CbxComuna.addItem(rss.getString(2));

            }

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(RegistarUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_CbxRegionActionPerformed

    private void BtnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegistrarActionPerformed
        Registros registro = new Registros();
        int validado = 0;
        LbErrorNombres.setVisible(false);
        LbErrorApepa.setVisible(false);
        LbErrorApMa.setVisible(false);
        LbErroRut.setVisible(false);
        LbErrorClave.setVisible(false);
        LbErroDireccion.setVisible(false);
        LbErrorCorreo.setVisible(false);
        LbErrorTelefono.setVisible(false);

        try {
            if (TxtNombre.getText().trim().length()<=0) {
                LbErrorNombres.setText("El nombre no puede estar vacio");
                LbErrorNombres.setVisible(true);
                validado++;
            };
            if(TxtApellidoPaterno.getText().trim().length()<=0){
                LbErrorApepa.setText("El apellido paterno no puede estar vacio");
                LbErrorApepa.setVisible(true);
                validado++;
            };
            if(TxtApellidoMaterno.getText().trim().length()<=0){
                LbErrorApMa.setText("El apellido materno no puede estar vacio");
                LbErrorApMa.setVisible(true);
                validado++;
            };
            if(TxtRut.getText().trim().length()<=0){
                LbErroRut.setText("El rut no puede estar vacio");
                LbErroRut.setVisible(true);
                validado++;
            };
            if(validacion.isValidRut(TxtRut.getText().trim())==false){
                LbErroRut.setText("Inserte rut sin punto y con guión");
                LbErroRut.setVisible(true);
                validado++;
            };
            if(TxtContraseña.getText().trim().length()<=0){
                LbErrorClave.setText("La clave no puede estar vacia");
                LbErrorClave.setVisible(true);
                validado++;
            };

            if(!TxtContraseña.getText().equals(TxtRepetirContraseña.getText())){
                LbErrorClave.setText("Contraseñas no son iguales");
                LbErrorClave.setVisible(true);
                validado++;

            }
            if(TxtDireccion.getText().trim().length()<=0){
                LbErroDireccion.setText("La direccion no puede estar vacia");
                LbErroDireccion.setVisible(true);
                validado++;
            };
            if(TxtCorreoElectronico.getText().trim().length()<=0){
                LbErrorCorreo.setText("El correo no puede estar vacio");
                LbErrorCorreo.setVisible(true);
                validado++;
            };
            if(TxtTelefono.getText().trim().length()<=0){
                LbErrorTelefono.setText("El telefono no puede estar vacio");
                LbErrorTelefono.setVisible(true);
                validado++;
            };
            if(validacion.validacionNumeros(TxtNombre.getText())){
                LbErrorNombres.setText("El nombre no puede tener numeros");
                LbErrorNombres.setVisible(true);
                validado++;
            };
            if(validacion.validacionNumeros(TxtApellidoPaterno.getText())){
                LbErrorApepa.setText("El apellido no puede tener numeros");
                LbErrorApepa.setVisible(true);
                validado++;
            };
            if(validacion.validacionNumeros(TxtApellidoMaterno.getText())){
                LbErrorApMa.setText("El apellido no puede tener numeros");
                LbErrorApMa.setVisible(true);
                validado++;
            };
            if(validacion.validacionLetras(TxtTelefono.getText())){
                LbErrorTelefono.setText("El telefono no puede tener letras");
                LbErrorTelefono.setVisible(true);
                validado++;
            };
            //                if(validacion.validarRut(TxtRut.getText())){
                //                    LbErroRut.setText("Rut invalido");
                //                    LbErroRut.setVisible(true);
                //                };

            if(usuarioN.validarUsuario(TxtRut.getText())){
                LbErroRut.setText("El usuario ya existe");
                LbErroRut.setVisible(true);
                validado++;
            }
            
            if(validado>0){
                validado=0;
                JOptionPane.showMessageDialog(null, "Registro no completado","Usuario no registrado", JOptionPane.WARNING_MESSAGE);
            }
            else {
                HasharClave hs = new HasharClave();
                String ClaveHash = hs.MD5(TxtContraseña.getText());
                usuarioN.RegistrarUsuario( TxtDireccion.getText(),TxtApellidoPaterno.getText(),
                    "N",TxtRut.getText(), TxtApellidoMaterno.getText(),
                    ClaveHash,comuna.getIDxNombre(CbxComuna.getSelectedItem().toString()),
                    TxtNombre.getText(),tusuario.getIDxNombre(CbxRoles.getSelectedItem().toString()),
                    TxtCorreoElectronico.getText(),0,TxtTelefono.getText()
                );
                JOptionPane.showMessageDialog(null, "Registro completado","Usuario Registrado correctamente", JOptionPane.INFORMATION_MESSAGE);
            }

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(RegistarUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnRegistrarActionPerformed

    private void CbxComunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbxComunaActionPerformed
    
    }//GEN-LAST:event_CbxComunaActionPerformed

    private void TxtRepetirContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtRepetirContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtRepetirContraseñaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BtnCancelar;
    private javax.swing.JButton BtnRegistrar;
    public javax.swing.JComboBox<String> CbxComuna;
    private javax.swing.JComboBox<String> CbxEmpresa;
    public javax.swing.JComboBox<String> CbxRegion;
    public javax.swing.JComboBox<String> CbxRoles;
    public javax.swing.JComboBox<String> CbxTiendas;
    private javax.swing.JLabel LbErroDireccion;
    private javax.swing.JLabel LbErroRut;
    private javax.swing.JLabel LbErrorApMa;
    private javax.swing.JLabel LbErrorApepa;
    private javax.swing.JLabel LbErrorClave;
    private javax.swing.JLabel LbErrorCorreo;
    private javax.swing.JLabel LbErrorNombres;
    private javax.swing.JLabel LbErrorTelefono;
    private javax.swing.JLabel Region;
    private javax.swing.JTextField TxtApellidoMaterno;
    private javax.swing.JTextField TxtApellidoPaterno;
    private javax.swing.JPasswordField TxtContraseña;
    private javax.swing.JTextField TxtCorreoElectronico;
    private javax.swing.JTextField TxtDireccion;
    private javax.swing.JTextField TxtNombre;
    private javax.swing.JPasswordField TxtRepetirContraseña;
    private javax.swing.JTextField TxtRut;
    private javax.swing.JTextField TxtTelefono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
